// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-is5nC4iWU3GbctkaSRvBK9tFJBGhcbQ',
    appId: '1:64059162515:web:ef5181cea2420319f9f266',
    messagingSenderId: '64059162515',
    projectId: 'lit-habit-f38b6',
    authDomain: 'lit-habit-f38b6.firebaseapp.com',
    storageBucket: 'lit-habit-f38b6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChDpFvjPmwXhv5Wcyd956pAajZURBj2Pg',
    appId: '1:64059162515:android:f9271246045b06aaf9f266',
    messagingSenderId: '64059162515',
    projectId: 'lit-habit-f38b6',
    storageBucket: 'lit-habit-f38b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeFIIByNdKz0032pGbH5ZhT6sBhOBtYQM',
    appId: '1:64059162515:ios:d7556a162b55b460f9f266',
    messagingSenderId: '64059162515',
    projectId: 'lit-habit-f38b6',
    storageBucket: 'lit-habit-f38b6.appspot.com',
    iosClientId: '64059162515-mfolkov4m7g8u5aie6sulmd26bpfpens.apps.googleusercontent.com',
    iosBundleId: 'com.example.lithabit',
  );
}
